---
- name: Download grr-client from grr-server
  get_url: 
    url: http://localhost/api/config/binaries-blobs/EXECUTABLE/linux/installers/grr_3.4.0.8_amd64.deb
    dest: /tmp/grr_amd64.deb
    username: admin
    password: password

- name: Install grr-client
  apt:
    deb: /tmp/grr_amd64.deb
    state: present

- name: Ensure grr-client is running
  service:
    name: grr
    state: started