---
- name: Setup GRR Server
  copy:
    src: files/grr 
    dest: '{{grr_location}}'
    owner: root
    group: root

- name: Start GRR Server
  docker_compose:
    project_src: "{{grr_location}}/grr"
    state: present
  register: output

- debug:
    var: output

- name: Wait for GRR Server to Start
  uri:
    url: "http://127.0.0.1:8000/"
    status_code: 200
    user: admin
    password: password
  register: result
  until: result.status == 200
  retries: 60
  delay: 5