---
- name: Setup GRR Server
  copy:
    src: files/grr 
    dest: '{{grr_location}}'
    owner: root
    group: root

- name: Start GRR Server
  docker_compose:
    project_src: "{{grr_location}}/grr"
    state: present
  register: output

- debug:
    var: output