version: "3.3"
services:
  forensics_server:
    build:
      context: ./server
    image: forensics-server
    container_name: forensics_server
    depends_on: redis
    environment: 
        - REDIS_HOST=redis
        - REDIS_PORT=6379
        - REDIS_PASSWORD=password
    ports: 
        - "80:80"
  redis:
    image: bitnami/redis:latest
    container_name: redis
    environment: 
        - ALLOW_EMPTY_PASSWORD=yes
        - REDIS_PASSWORD=password
    ports: 
        - "6379"
    volumes: 
        - redis-data:/bitnami/redis/data

volumes: 
    redis-data:
        driver: local