version: '3'

services:
  grr-server:
    container_name: grr-server
    image: grrdocker/grr
    environment: 
      - EXTERNAL_HOSTNAME=localhost
      - ADMIN_PASSWORD=password  
    ports:
      - "0.0.0.0:80:8000"
      - "0.0.0.0:8080:8080"
    volumes: 
      - ./grr-server/grr-server.yaml:/usr/share/grr-server/install_data/etc/grr-server.yaml